general.live_config_reload = true
general.import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
blur = true

[window.padding]
x = 25
y = 20

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[keyboard]
bindings = [
{ key = "N", mods = "Control", action = "SpawnNewInstance" },
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
